# Generated by Django 4.2.13 on 2026-02-04 19:34

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import sows.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("identity", "0001_initial"),
        (
            "templates",
            "0002_rename_templates_t_org_id_88552c_idx_templates_t_org_id_2f8a80_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("work_items", "0005_task_assignee_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoW",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_sows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SoWVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("variables_json", models.JSONField(blank=True, default=dict)),
                ("body_markdown", models.TextField(blank=True)),
                ("body_html", models.TextField(blank=True)),
                ("content_sha256", models.CharField(blank=True, max_length=64)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_signature", "Pending signature"),
                            ("signed", "Signed"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_sow_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="sows.sow",
                    ),
                ),
                (
                    "template_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sow_versions",
                        to="templates.templateversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SoWSigner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("decision_comment", models.TextField(blank=True)),
                ("typed_signature", models.CharField(blank=True, max_length=200)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "signer_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sow_signers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sow_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signers",
                        to="sows.sowversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SoWPdfArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("celery_task_id", models.CharField(blank=True, max_length=100)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("blocked_urls", models.JSONField(blank=True, default=list)),
                ("missing_images", models.JSONField(blank=True, default=list)),
                ("error_code", models.CharField(blank=True, max_length=100)),
                ("error_message", models.TextField(blank=True)),
                ("qa_report", models.JSONField(blank=True, default=dict)),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        max_length=500,
                        null=True,
                        upload_to=sows.models.sow_pdf_upload_to,
                    ),
                ),
                ("pdf_content_type", models.CharField(blank=True, max_length=100)),
                ("pdf_size_bytes", models.PositiveBigIntegerField(default=0)),
                ("pdf_sha256", models.CharField(blank=True, max_length=64)),
                ("pdf_rendered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sow_version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_artifact",
                        to="sows.sowversion",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sow",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="sows.sowversion",
            ),
        ),
        migrations.AddField(
            model_name="sow",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="sows", to="identity.org"
            ),
        ),
        migrations.AddField(
            model_name="sow",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sows",
                to="work_items.project",
            ),
        ),
        migrations.AddField(
            model_name="sow",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sows",
                to="templates.template",
            ),
        ),
        migrations.AddIndex(
            model_name="sowversion",
            index=models.Index(fields=["sow", "created_at"], name="sows_sowver_sow_id_b58624_idx"),
        ),
        migrations.AddIndex(
            model_name="sowversion",
            index=models.Index(
                fields=["sow", "status", "created_at"], name="sows_sowver_sow_id_eecded_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sowversion",
            constraint=models.UniqueConstraint(
                fields=("sow", "version"), name="sow_version_unique_per_sow"
            ),
        ),
        migrations.AddIndex(
            model_name="sowsigner",
            index=models.Index(
                fields=["sow_version", "status", "created_at"],
                name="sows_sowsig_sow_ver_386e3b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sowsigner",
            index=models.Index(
                fields=["signer_user", "created_at"], name="sows_sowsig_signer__ac318c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sowsigner",
            constraint=models.UniqueConstraint(
                fields=("sow_version", "signer_user"), name="sow_signer_unique_per_version_user"
            ),
        ),
        migrations.AddIndex(
            model_name="sowpdfartifact",
            index=models.Index(
                fields=["sow_version", "created_at"], name="sows_sowpdf_sow_ver_8af6f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sowpdfartifact",
            index=models.Index(
                fields=["status", "created_at"], name="sows_sowpdf_status_365058_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sow",
            index=models.Index(fields=["org", "created_at"], name="sows_sow_org_id_3736f5_idx"),
        ),
        migrations.AddIndex(
            model_name="sow",
            index=models.Index(
                fields=["org", "project", "created_at"], name="sows_sow_org_id_3d49be_idx"
            ),
        ),
    ]
