# Generated by Django 4.2.13 on 2026-02-03 21:57

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("work_items", "0003_project_workflow_subtask_workflow_stage_and_more"),
        ("identity", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomFieldDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("date", "Date"),
                            ("select", "Select"),
                            ("multi_select", "Multi-select"),
                        ],
                        max_length=20,
                    ),
                ),
                ("options", models.JSONField(blank=True, default=list)),
                ("client_safe", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_field_definitions",
                        to="identity.org",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_field_definitions",
                        to="work_items.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomFieldValue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "work_item_type",
                    models.CharField(
                        choices=[("task", "Task"), ("subtask", "Subtask")], max_length=10
                    ),
                ),
                ("work_item_id", models.UUIDField()),
                ("value_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="customization.customfielddefinition",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_field_values",
                        to="identity.org",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_field_values",
                        to="work_items.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SavedView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("client_safe", models.BooleanField(default=False)),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("sort", models.JSONField(blank=True, default=dict)),
                ("group_by", models.CharField(default="none", max_length=50)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_views",
                        to="identity.org",
                    ),
                ),
                (
                    "owner_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_views",
                        to="work_items.project",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["org", "project", "owner_user", "created_at"],
                        name="customizati_org_id_cb836f_idx",
                    ),
                    models.Index(
                        fields=["org", "project", "owner_user", "archived_at"],
                        name="customizati_org_id_12428b_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="savedview",
            constraint=models.UniqueConstraint(
                fields=("owner_user", "project", "name"), name="unique_saved_view_name_per_owner"
            ),
        ),
        migrations.AddIndex(
            model_name="customfieldvalue",
            index=models.Index(
                fields=["project", "work_item_type", "work_item_id"],
                name="customizati_project_db6856_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customfieldvalue",
            index=models.Index(
                fields=["field", "work_item_type", "work_item_id"],
                name="customizati_field_i_632d44_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="customfieldvalue",
            constraint=models.UniqueConstraint(
                fields=("field", "work_item_type", "work_item_id"),
                name="unique_custom_field_value_per_work_item",
            ),
        ),
        migrations.AddIndex(
            model_name="customfielddefinition",
            index=models.Index(
                fields=["project", "created_at"], name="customizati_project_e1066d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customfielddefinition",
            index=models.Index(
                fields=["project", "archived_at"], name="customizati_project_c3b03d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customfielddefinition",
            index=models.Index(
                fields=["org", "project", "client_safe"], name="customizati_org_id_18954d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="customfielddefinition",
            constraint=models.UniqueConstraint(
                fields=("project", "name"), name="unique_custom_field_name_per_project"
            ),
        ),
    ]
