# Generated by Django 4.2.13 on 2026-02-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgmembership",
            name="availability_hours_per_week",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orgmembership",
            name="availability_next_available_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orgmembership",
            name="availability_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="orgmembership",
            name="availability_status",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("available", "Available"),
                    ("limited", "Limited"),
                    ("unavailable", "Unavailable"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="orgmembership",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="orgmembership",
            name="skills",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="orgmembership",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
