# Generated by Django 4.2.13 on 2026-02-13 10:03

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0002_orgmembership_availability_hours_per_week_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orginvite",
            name="message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("full_name", models.CharField(blank=True, default="", max_length=200)),
                ("preferred_name", models.CharField(blank=True, default="", max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("bio", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                ("timezone", models.CharField(blank=True, default="UTC", max_length=64)),
                ("location", models.CharField(blank=True, default="", max_length=200)),
                ("phone", models.CharField(blank=True, default="", max_length=50)),
                ("slack_handle", models.CharField(blank=True, default="", max_length=100)),
                ("linkedin_url", models.URLField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="people",
                        to="identity.org",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="people",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="orginvite",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invites",
                to="identity.person",
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(fields=["org", "created_at"], name="identity_pe_org_id_0f750f_idx"),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(fields=["org", "updated_at"], name="identity_pe_org_id_f133f0_idx"),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(fields=["org", "full_name"], name="identity_pe_org_id_39caa4_idx"),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(fields=["org", "email"], name="identity_pe_org_id_3d0315_idx"),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(fields=["org", "user"], name="identity_pe_org_id_4d5d7b_idx"),
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.UniqueConstraint(
                condition=models.Q(("email__isnull", False)),
                fields=("org", "email"),
                name="unique_person_email_per_org_when_present",
            ),
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("org", "user"),
                name="unique_person_user_per_org_when_present",
            ),
        ),
    ]
