# Generated by Django 4.2.13 on 2026-02-13 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_backfill_people_from_memberships'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonAvailabilityException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('time_off', 'Time off'), ('available', 'Available')], max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_person_availability_exceptions', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_exceptions', to='identity.person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonAvailabilityWeeklyWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_weekly_windows', to='identity.person')),
            ],
            options={
                'indexes': [models.Index(fields=['person', 'weekday', 'start_time'], name='identity_pe_person__59b32e_idx'), models.Index(fields=['person', 'created_at'], name='identity_pe_person__d97760_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='personavailabilityweeklywindow',
            constraint=models.CheckConstraint(check=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='person_weekly_window_weekday_range_0_6'),
        ),
        migrations.AddConstraint(
            model_name='personavailabilityweeklywindow',
            constraint=models.CheckConstraint(check=models.Q(('start_time__lt', models.F('end_time'))), name='person_weekly_window_start_time_lt_end_time'),
        ),
        migrations.AddConstraint(
            model_name='personavailabilityweeklywindow',
            constraint=models.UniqueConstraint(fields=('person', 'weekday', 'start_time', 'end_time'), name='person_weekly_window_unique_person_day_times'),
        ),
        migrations.AddIndex(
            model_name='personavailabilityexception',
            index=models.Index(fields=['person', 'starts_at'], name='identity_pe_person__5f35b0_idx'),
        ),
        migrations.AddIndex(
            model_name='personavailabilityexception',
            index=models.Index(fields=['person', 'created_at'], name='identity_pe_person__7fed45_idx'),
        ),
        migrations.AddConstraint(
            model_name='personavailabilityexception',
            constraint=models.CheckConstraint(check=models.Q(('starts_at__lt', models.F('ends_at'))), name='person_availability_exception_starts_at_lt_ends_at'),
        ),
    ]
