# Generated by Django 4.2.13 on 2026-02-18 21:52

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0006_person_gitlab_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonMessageThread",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_person_message_threads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_threads",
                        to="identity.person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("body_markdown", models.TextField()),
                ("body_html", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authored_person_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="identity.personmessagethread",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonContactEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("note", "Note"),
                            ("call", "Call"),
                            ("email", "Email"),
                            ("meeting", "Meeting"),
                        ],
                        default="note",
                        max_length=20,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("summary", models.CharField(blank=True, default="", max_length=200)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_person_contact_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_entries",
                        to="identity.person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("amount_cents", models.PositiveIntegerField()),
                ("effective_date", models.DateField()),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_person_rates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="identity.person",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["person", "effective_date"], name="identity_pe_person__a8eaf1_idx"
                    ),
                    models.Index(
                        fields=["person", "created_at"], name="identity_pe_person__5cc347_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PersonPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("amount_cents", models.PositiveIntegerField()),
                ("paid_date", models.DateField()),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_person_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="identity.person",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["person", "paid_date"], name="identity_pe_person__dc5838_idx"
                    ),
                    models.Index(
                        fields=["person", "created_at"], name="identity_pe_person__490508_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="personmessagethread",
            index=models.Index(
                fields=["person", "updated_at"], name="identity_pe_person__8571a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personmessagethread",
            index=models.Index(
                fields=["person", "created_at"], name="identity_pe_person__6cd8c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personmessage",
            index=models.Index(
                fields=["thread", "created_at"], name="identity_pe_thread__01ab06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personmessage",
            index=models.Index(
                fields=["author_user", "created_at"], name="identity_pe_author__ebcdc8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personcontactentry",
            index=models.Index(
                fields=["person", "occurred_at"], name="identity_pe_person__9676d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personcontactentry",
            index=models.Index(
                fields=["person", "created_at"], name="identity_pe_person__2f7710_idx"
            ),
        ),
    ]
