# Generated by Django 4.2.13 on 2026-02-19 17:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0002_orgmembership_legacy_columns_nullable"),
        (
            "identity",
            "0007_personmessagethread_personmessage_personcontactentry_and_more",
        ),
    ]

    operations = []
