# Generated by Django 4.2.13 on 2026-02-25 00:00

from django.db import migrations, models

import identity.models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0012_globaldefaults_orgdefaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globaldefaults",
            name="workflow_stage_template",
            field=models.JSONField(
                blank=True,
                default=identity.models.default_workflow_stage_template,
            ),
        ),
    ]
