# Generated by Django 4.2.13 on 2026-02-03 17:40

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflows",
                        to="identity.org",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkflowStage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField()),
                ("is_done", models.BooleanField(default=False)),
                ("is_qa", models.BooleanField(default=False)),
                ("counts_as_wip", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["workflow", "order"], name="workflows_w_workflo_3917c8_idx"
                    ),
                    models.Index(
                        fields=["workflow", "created_at"], name="workflows_w_workflo_059cea_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="workflowstage",
            constraint=models.UniqueConstraint(
                fields=("workflow", "order"), name="unique_workflow_stage_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowstage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_done", True)),
                fields=("workflow",),
                name="unique_workflow_done_stage",
            ),
        ),
        migrations.AddIndex(
            model_name="workflow",
            index=models.Index(fields=["org", "created_at"], name="workflows_w_org_id_b13edc_idx"),
        ),
        migrations.AddIndex(
            model_name="workflow",
            index=models.Index(fields=["org", "updated_at"], name="workflows_w_org_id_928146_idx"),
        ),
    ]
