# Generated by Django 4.2.13 on 2026-02-04 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_keys', '0001_initial'),
        ('identity', '0001_initial'),
        ('reports', '0002_rename_reports_rep_org_id_9be94a_idx_reports_rep_org_id_2b0ebc_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('output_markdown', models.TextField(blank=True)),
                ('output_html', models.TextField(blank=True)),
                ('last_access_at', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('created_by_api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_share_links', to='api_keys.apikey')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_share_links', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='identity.org')),
                ('report_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='reports.reportrun')),
            ],
        ),
        migrations.CreateModel(
            name='ShareLinkAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('share_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='share_links.sharelink')),
            ],
            options={
                'indexes': [models.Index(fields=['share_link', 'accessed_at'], name='share_links_share_l_de709c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sharelink',
            index=models.Index(fields=['org', 'created_at'], name='share_links_org_id_df3947_idx'),
        ),
        migrations.AddIndex(
            model_name='sharelink',
            index=models.Index(fields=['org', 'report_run', 'created_at'], name='share_links_org_id_a488f8_idx'),
        ),
        migrations.AddIndex(
            model_name='sharelink',
            index=models.Index(fields=['token_hash'], name='share_links_token_h_23a3bc_idx'),
        ),
        migrations.AddIndex(
            model_name='sharelink',
            index=models.Index(fields=['org', 'report_run', 'revoked_at'], name='share_links_org_id_b3edbc_idx'),
        ),
        migrations.AddIndex(
            model_name='sharelink',
            index=models.Index(fields=['org', 'report_run', 'expires_at'], name='share_links_org_id_da9bda_idx'),
        ),
        migrations.AddConstraint(
            model_name='sharelink',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('created_by_api_key__isnull', True), ('created_by_user__isnull', False)), models.Q(('created_by_api_key__isnull', False), ('created_by_user__isnull', True)), _connector='OR'), name='share_links_created_by_xor'),
        ),
    ]
