# Generated by Django 4.2.13 on 2026-02-03 15:20

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Epic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("backlog", "Backlog"),
                            ("in_progress", "In progress"),
                            ("qa", "QA"),
                            ("done", "Done"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("backlog", "Backlog"),
                            ("in_progress", "In progress"),
                            ("qa", "QA"),
                            ("done", "Done"),
                        ],
                        default="backlog",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "epic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="work_items.epic",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subtask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("backlog", "Backlog"),
                            ("in_progress", "In progress"),
                            ("qa", "QA"),
                            ("done", "Done"),
                        ],
                        default="backlog",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtasks",
                        to="work_items.task",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="identity.org",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="epic",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="epics",
                to="work_items.project",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["epic", "created_at"], name="work_items__epic_id_97ea29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["epic", "status"], name="work_items__epic_id_0ac0f6_idx"),
        ),
        migrations.AddIndex(
            model_name="subtask",
            index=models.Index(
                fields=["task", "created_at"], name="work_items__task_id_87065d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subtask",
            index=models.Index(fields=["task", "status"], name="work_items__task_id_70bb29_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["org", "created_at"], name="work_items__org_id_c97979_idx"),
        ),
        migrations.AddIndex(
            model_name="epic",
            index=models.Index(
                fields=["project", "created_at"], name="work_items__project_067921_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="epic",
            index=models.Index(fields=["project", "status"], name="work_items__project_64950c_idx"),
        ),
    ]
