# Generated by Django 4.2.13 on 2026-02-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("work_items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subtask",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subtask",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="subtask",
            constraint=models.CheckConstraint(
                check=models.Q(start_date__isnull=True)
                | models.Q(end_date__isnull=True)
                | models.Q(start_date__lte=models.F("end_date")),
                name="subtask_start_date_lte_end_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                check=models.Q(start_date__isnull=True)
                | models.Q(end_date__isnull=True)
                | models.Q(start_date__lte=models.F("end_date")),
                name="task_start_date_lte_end_date",
            ),
        ),
    ]
