# Generated by Django 4.2.13 on 2026-02-03 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0001_initial"),
        ("work_items", "0002_task_subtask_scheduling_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="workflow",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to="workflows.workflow",
            ),
        ),
        migrations.AddField(
            model_name="subtask",
            name="workflow_stage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subtasks",
                to="workflows.workflowstage",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["org", "workflow"], name="work_items__org_id_52ec1c_idx"),
        ),
    ]
