# Generated by Django 4.2.13 on 2026-02-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("work_items", "0003_project_workflow_subtask_workflow_stage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="client_safe",
            field=models.BooleanField(default=False),
        ),
    ]

