# Generated by Django 4.2.13 on 2026-02-19 01:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("work_items", "0006_projectmembership_and_more"),
        ("work_items", "0006_task_workflow_stage_progress_policies_and_backfill"),
    ]

    operations = []
