# Generated by Django 4.2.13 on 2026-02-13 18:56

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "work_items",
            "0007_merge_0006_projectmembership_and_more_0006_task_workflow_stage_progress_policies_and_backfill",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_task_participants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual_participants",
                        to="work_items.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_participants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["task", "created_at"], name="work_items__task_id_25e8c6_idx"
                    ),
                    models.Index(
                        fields=["user", "created_at"], name="work_items__user_id_197314_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="taskparticipant",
            constraint=models.UniqueConstraint(
                fields=("task", "user"), name="task_participant_unique_task_user"
            ),
        ),
    ]
