# Generated by Django 4.2.13 on 2026-02-19 17:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("work_items", "0007_project_client_access"),
        ("work_items", "0008_task_participants"),
    ]

    operations = []

