# Generated by Django 4.2.13 on 2026-02-04 16:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("templates", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="template",
            new_name="templates_t_org_id_2f8a80_idx",
            old_name="templates_t_org_id_88552c_idx",
        ),
        migrations.RenameIndex(
            model_name="template",
            new_name="templates_t_org_id_1d7b80_idx",
            old_name="templates_t_org_id_3d4c6f_idx",
        ),
        migrations.RenameIndex(
            model_name="templateversion",
            new_name="templates_t_templat_aad4d0_idx",
            old_name="templates_t_template_6445df_idx",
        ),
        migrations.RenameIndex(
            model_name="templateversion",
            new_name="templates_t_templat_386014_idx",
            old_name="templates_t_template_675374_idx",
        ),
    ]
