# Generated by Django 4.2.13 on 2026-02-04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("identity", "0001_initial"),
        ("templates", "0001_initial"),
        ("work_items", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scope", models.JSONField(blank=True, default=dict)),
                ("output_markdown", models.TextField(blank=True)),
                ("output_html", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_report_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_runs",
                        to="identity.org",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_runs",
                        to="work_items.project",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_runs",
                        to="templates.template",
                    ),
                ),
                (
                    "template_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_runs",
                        to="templates.templateversion",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["org", "created_at"],
                        name="reports_rep_org_id_9be94a_idx",
                    ),
                    models.Index(
                        fields=["org", "project", "created_at"],
                        name="reports_rep_org_id_a4b68c_idx",
                    ),
                    models.Index(
                        fields=["template", "created_at"],
                        name="reports_rep_template_e35b84_idx",
                    ),
                ],
            },
        ),
    ]
