# Generated by Django 4.2.13 on 2026-02-04 16:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="reportrun",
            new_name="reports_rep_org_id_2b0ebc_idx",
            old_name="reports_rep_org_id_9be94a_idx",
        ),
        migrations.RenameIndex(
            model_name="reportrun",
            new_name="reports_rep_org_id_8ae9a2_idx",
            old_name="reports_rep_org_id_a4b68c_idx",
        ),
        migrations.RenameIndex(
            model_name="reportrun",
            new_name="reports_rep_templat_e799f8_idx",
            old_name="reports_rep_template_e35b84_idx",
        ),
    ]
