# Generated by Django 4.2.13 on 2026-02-05 00:00

import uuid

import django.db.models.deletion
from django.db import migrations, models

import reports.models


class Migration(migrations.Migration):
    dependencies = [
        (
            "reports",
            "0002_rename_reports_rep_org_id_9be94a_idx_reports_rep_org_id_2b0ebc_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="reportrun",
            name="pdf_content_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="reportrun",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=reports.models.report_pdf_upload_to,
            ),
        ),
        migrations.AddField(
            model_name="reportrun",
            name="pdf_rendered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reportrun",
            name="pdf_sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="reportrun",
            name="pdf_size_bytes",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="ReportRunPdfRenderLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("celery_task_id", models.CharField(blank=True, max_length=100)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("blocked_urls", models.JSONField(blank=True, default=list)),
                ("missing_images", models.JSONField(blank=True, default=list)),
                ("error_code", models.CharField(blank=True, max_length=100)),
                ("error_message", models.TextField(blank=True)),
                ("qa_report", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_render_logs",
                        to="reports.reportrun",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["report_run", "created_at"],
                        name="reports_rep_report__7bb1d1_idx",
                    ),
                    models.Index(
                        fields=["report_run", "status", "created_at"],
                        name="reports_rep_report__96ec5d_idx",
                    ),
                ],
            },
        ),
    ]
