# Generated by Django 4.2.13 on 2026-02-04 16:56

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "templates",
            "0002_rename_templates_t_org_id_88552c_idx_templates_t_org_id_2f8a80_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("identity", "0001_initial"),
        ("work_items", "0005_task_assignee_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboundDraft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("email", "Email"), ("comment", "Comment")], max_length=20
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("sent", "Sent")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(blank=True, default="", max_length=300)),
                ("body_markdown", models.TextField()),
                ("to_user_ids", models.JSONField(blank=True, default=list)),
                (
                    "work_item_type",
                    models.CharField(
                        blank=True,
                        choices=[("task", "Task"), ("epic", "Epic")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("work_item_id", models.UUIDField(blank=True, null=True)),
                ("comment_client_safe", models.BooleanField(default=False)),
                ("sent_comment_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_outbound_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outbound_drafts",
                        to="identity.org",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outbound_drafts",
                        to="work_items.project",
                    ),
                ),
                (
                    "sent_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_outbound_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbound_drafts",
                        to="templates.template",
                    ),
                ),
                (
                    "template_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbound_drafts",
                        to="templates.templateversion",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["project", "created_at"], name="outbound_co_project_ca7511_idx"
                    ),
                    models.Index(
                        fields=["org", "created_at"], name="outbound_co_org_id_e003ac_idx"
                    ),
                    models.Index(
                        fields=["project", "status", "created_at"],
                        name="outbound_co_project_33b07d_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="outbounddraft",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("type", "email"), ("work_item_type__isnull", True)),
                    models.Q(("type", "comment"), ("work_item_type__isnull", False)),
                    _connector="OR",
                ),
                name="outbound_draft_work_item_required_for_comments",
            ),
        ),
    ]
