# Generated by Django 4.2.13 on 2026-02-04 00:52

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("identity", "0001_initial"),
        ("work_items", "0003_project_workflow_subtask_workflow_stage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgGitLabIntegration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("base_url", models.URLField(max_length=500)),
                ("token_ciphertext", models.TextField(blank=True, null=True)),
                ("token_set_at", models.DateTimeField(blank=True, null=True)),
                ("token_rotated_at", models.DateTimeField(blank=True, null=True)),
                ("webhook_secret_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "org",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gitlab",
                        to="identity.org",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GitLabWebhookDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("event_uuid", models.CharField(blank=True, max_length=64, null=True)),
                ("event_type", models.CharField(blank=True, default="", max_length=100)),
                ("project_path", models.CharField(blank=True, default="", max_length=500)),
                ("gitlab_type", models.CharField(blank=True, default="", max_length=20)),
                ("gitlab_iid", models.PositiveIntegerField(blank=True, null=True)),
                ("payload_sha256", models.CharField(max_length=64)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                ("last_error", models.TextField(blank=True, default="")),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gitlab_webhooks",
                        to="identity.org",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskGitLabLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("web_url", models.URLField(max_length=1000)),
                ("project_path", models.CharField(max_length=500)),
                (
                    "gitlab_type",
                    models.CharField(
                        choices=[("issue", "Issue"), ("mr", "Merge Request")], max_length=20
                    ),
                ),
                ("gitlab_iid", models.PositiveIntegerField()),
                ("cached_title", models.CharField(blank=True, default="", max_length=500)),
                ("cached_state", models.CharField(blank=True, default="", max_length=50)),
                ("cached_labels", models.JSONField(blank=True, default=list)),
                ("cached_assignees", models.JSONField(blank=True, default=list)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_error_code", models.CharField(blank=True, default="", max_length=100)),
                ("last_sync_error_at", models.DateTimeField(blank=True, null=True)),
                ("rate_limited_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gitlab_links",
                        to="work_items.task",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["task", "created_at"], name="integration_task_id_c38165_idx"
                    ),
                    models.Index(
                        fields=["project_path", "gitlab_type", "gitlab_iid"],
                        name="integration_project_5b5285_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="taskgitlablink",
            constraint=models.UniqueConstraint(
                fields=("task", "web_url"), name="unique_task_gitlab_link_url"
            ),
        ),
        migrations.AddIndex(
            model_name="orggitlabintegration",
            index=models.Index(fields=["org", "updated_at"], name="integration_org_id_c87a53_idx"),
        ),
        migrations.AddIndex(
            model_name="gitlabwebhookdelivery",
            index=models.Index(fields=["org", "received_at"], name="integration_org_id_49ac89_idx"),
        ),
        migrations.AddIndex(
            model_name="gitlabwebhookdelivery",
            index=models.Index(fields=["event_uuid"], name="integration_event_u_b0487c_idx"),
        ),
        migrations.AddConstraint(
            model_name="gitlabwebhookdelivery",
            constraint=models.UniqueConstraint(
                condition=models.Q(("event_uuid__isnull", False)),
                fields=("org", "event_uuid"),
                name="unique_org_gitlab_webhook_event_uuid",
            ),
        ),
    ]
