# Generated by Django 4.2.13 on 2026-02-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskgitlablink",
            name="cached_participants",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
