# Generated by Django 4.2.13 on 2026-02-25 00:00

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0002_gitlab_cached_participants"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalGitLabIntegration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        primary_key=True,
                        default=uuid.uuid4,
                        editable=False,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(default="default", max_length=50, unique=True)),
                ("base_url", models.URLField(blank=True, default="", max_length=500)),
                ("token_ciphertext", models.TextField(blank=True, null=True)),
                ("token_set_at", models.DateTimeField(blank=True, null=True)),
                ("token_rotated_at", models.DateTimeField(blank=True, null=True)),
                ("webhook_secret_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["key", "updated_at"],
                        name="integrations_g_key_9bba84_idx",
                    ),
                ],
            },
        ),
    ]
