# Generated by Django 4.2.13 on 2026-02-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collaboration", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="attachment",
            name="attachment_exactly_one_target",
        ),
        migrations.RemoveConstraint(
            model_name="comment",
            name="comment_exactly_one_target",
        ),
        migrations.RenameIndex(
            model_name="attachment",
            new_name="collaborati_org_id_fe7a11_idx",
            old_name="collaboration_org_id_0f1a80_idx",
        ),
        migrations.RenameIndex(
            model_name="attachment",
            new_name="collaborati_task_id_eab2f9_idx",
            old_name="collaboration_task_id_e70ef3_idx",
        ),
        migrations.RenameIndex(
            model_name="attachment",
            new_name="collaborati_epic_id_61b9bc_idx",
            old_name="collaboration_epic_id_bca5e1_idx",
        ),
        migrations.RenameIndex(
            model_name="attachment",
            new_name="collaborati_comment_8f168c_idx",
            old_name="collaboration_comment_id_34b0e3_idx",
        ),
        migrations.RenameIndex(
            model_name="comment",
            new_name="collaborati_org_id_5d0af7_idx",
            old_name="collaboration_org_id_73df4d_idx",
        ),
        migrations.RenameIndex(
            model_name="comment",
            new_name="collaborati_task_id_b48cf9_idx",
            old_name="collaboration_task_id_3e6b69_idx",
        ),
        migrations.RenameIndex(
            model_name="comment",
            new_name="collaborati_epic_id_258c83_idx",
            old_name="collaboration_epic_id_986772_idx",
        ),
        migrations.AddConstraint(
            model_name="attachment",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("epic__isnull", True), ("task__isnull", False)),
                    models.Q(("epic__isnull", False), ("task__isnull", True)),
                    _connector="OR",
                ),
                name="attachment_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="comment",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("epic__isnull", True), ("task__isnull", False)),
                    models.Q(("epic__isnull", False), ("task__isnull", True)),
                    _connector="OR",
                ),
                name="comment_exactly_one_target",
            ),
        ),
    ]
