# Generated by Django 4.2.13 on 2026-02-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collaboration", "0002_remove_attachment_attachment_exactly_one_target_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="client_safe",
            field=models.BooleanField(default=False),
        ),
    ]
