# Generated by Django 4.2.13 on 2026-02-03 14:04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("identity", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("project_id", models.UUIDField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("prefix", models.CharField(max_length=40, unique=True)),
                ("secret_hash", models.CharField(max_length=128)),
                ("scopes", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("rotated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="identity.org",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["org", "created_at"], name="api_keys_ap_org_id_8eb0d2_idx"
                    ),
                    models.Index(
                        fields=["org", "revoked_at"], name="api_keys_ap_org_id_3f104e_idx"
                    ),
                ],
            },
        ),
    ]
