# Generated by Django 4.2.13 on 2026-02-04 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("outbound_comms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifications", "0001_initial"),
        ("work_items", "0005_task_assignee_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaildeliverylog",
            name="outbound_draft",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_deliveries",
                to="outbound_comms.outbounddraft",
            ),
        ),
        migrations.AddField(
            model_name="emaildeliverylog",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_deliveries",
                to="work_items.project",
            ),
        ),
        migrations.AddField(
            model_name="emaildeliverylog",
            name="recipient_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="email_deliveries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="projectnotificationsetting",
            index=models.Index(
                fields=["project", "event_type", "channel"], name="notificatio_project_1f0a4d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectnotificationsetting",
            constraint=models.UniqueConstraint(
                fields=("project", "event_type", "channel"),
                name="unique_project_notification_setting_per_project_event_channel",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationpreference",
            index=models.Index(fields=["user", "project"], name="notificatio_user_id_ad7bb5_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationpreference",
            index=models.Index(
                fields=["project", "event_type", "channel"], name="notificatio_project_1ccea1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationpreference",
            constraint=models.UniqueConstraint(
                fields=("user", "project", "event_type", "channel"),
                name="unique_notification_preference_per_user_project_event_channel",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationevent",
            index=models.Index(fields=["org", "created_at"], name="notificatio_org_id_028e69_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationevent",
            index=models.Index(
                fields=["org", "event_type", "created_at"], name="notificatio_org_id_a58e58_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationevent",
            index=models.Index(
                fields=["project", "created_at"], name="notificatio_project_2d7a57_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inappnotification",
            index=models.Index(
                fields=["recipient_user", "created_at"], name="notificatio_recipie_e8913d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inappnotification",
            index=models.Index(
                fields=["recipient_user", "project", "created_at"],
                name="notificatio_recipie_f26c0a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inappnotification",
            index=models.Index(
                fields=["recipient_user", "read_at", "created_at"],
                name="notificatio_recipie_238f42_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="inappnotification",
            constraint=models.UniqueConstraint(
                fields=("event", "recipient_user"),
                name="unique_in_app_notification_per_event_recipient",
            ),
        ),
        migrations.AddIndex(
            model_name="emaildeliverylog",
            index=models.Index(fields=["org", "queued_at"], name="notificatio_org_id_b18540_idx"),
        ),
        migrations.AddIndex(
            model_name="emaildeliverylog",
            index=models.Index(
                fields=["project", "queued_at"], name="notificatio_project_77ad19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emaildeliverylog",
            index=models.Index(
                fields=["project", "status", "queued_at"], name="notificatio_project_45a114_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="emaildeliverylog",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("notification_event__isnull", False), ("outbound_draft__isnull", True)
                    ),
                    models.Q(
                        ("notification_event__isnull", True), ("outbound_draft__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="email_delivery_exactly_one_source",
            ),
        ),
    ]
