# Generated by Django 4.2.13 on 2026-02-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationpreference",
            name="channel",
            field=models.CharField(
                choices=[("in_app", "In app"), ("email", "Email"), ("push", "Push")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="projectnotificationsetting",
            name="channel",
            field=models.CharField(
                choices=[("in_app", "In app"), ("email", "Email"), ("push", "Push")], max_length=20
            ),
        ),
    ]
