# Generated by Django 4.2.13 on 2026-02-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_alter_notificationpreference_channel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("assignment.changed", "Assignment changed"),
                    ("status.changed", "Status changed"),
                    ("comment.created", "Comment created"),
                    ("report.published", "Report published"),
                    ("person_message.created", "Message received"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("assignment.changed", "Assignment changed"),
                    ("status.changed", "Status changed"),
                    ("comment.created", "Comment created"),
                    ("report.published", "Report published"),
                    ("person_message.created", "Message received"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="projectnotificationsetting",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("assignment.changed", "Assignment changed"),
                    ("status.changed", "Status changed"),
                    ("comment.created", "Comment created"),
                    ("report.published", "Report published"),
                    ("person_message.created", "Message received"),
                ],
                max_length=100,
            ),
        ),
    ]
